#!/usr/bin/env bash
if [ $# != 1 ]
then
    echo -e "
Script usage: pgjedi (count|query|locks|size|conn)\n
count\t\t-- Show connections count
conn\t\t-- Show total connections count
query\t\t-- Show connections queries
locks\t\t-- Show locks
size\t\t-- Show databases size
"
    exit 1
fi


case $1 in
    count)
        psql -U postgres -c "SELECT client_addr, usename, datname, state, count(*) FROM pg_stat_activity WHERE pid <> pg_backend_pid() GROUP BY 1,2,3,4 ORDER BY 5 DESC;"
        ;;
    conn)
        psql -U postgres -c "SELECT count(*) as total_connections from (select pid from pg_stat_activity WHERE pid <> pg_backend_pid()) t;"
        ;;
    query)
        psql -U postgres -c "SELECT datname, usename, application_name, client_addr, state, query FROM pg_stat_activity WHERE pid <> pg_backend_pid();"
        ;;
    locks)
        psql -U postgres -c "SELECT locktype, relation::regclass, mode, transactionid AS tid, virtualtransaction AS vtid, pid, granted FROM pg_catalog.pg_locks l LEFT JOIN pg_catalog.pg_database db ON db.oid = l.database WHERE NOT pid = pg_backend_pid();"
        ;;
    size)
        psql -U postgres -c "SELECT pg_database.datname, round(pg_database_size(pg_database.datname)/1024/1024) AS size_MB FROM pg_database ORDER BY 2 DESC;"
        ;;
    *)
    echo -e "
Script usage: pgjedi (count|query|locks|size|conn)\n
count\t\t-- Show connections count
conn\t\t-- Show total connections count
query\t\t-- Show connections queries
locks\t\t-- Show locks
size\t\t-- Show databases size
"
    exit 1
    ;;
esac
exit 0
