#!/usr/bin/env bash

git config --local user.name "lcybrgl"
git config --local user.email "cybrg@inbox.ru"

git config --global alias.co checkout
git config --global alias.br branch
git config --global alias.ci commit
git config --global alias.st status
git config --global alias.unstage 'reset HEAD --'
git config --global alias.last 'log -10 HEAD --oneline'
